"""
quantize.py — turn a trained Scratch-Coder tier into a board-ready C header the
ESP32-S3 sketch compiles in. The big block matmul weights go to INT8 (per-tensor
symmetric scale — 1/4 the size); the small, precision-sensitive bits (embeddings,
output head, layernorms, all biases) stay float32.

    python quantize.py --tier featherweight

Reads web/tiers/<tier>/{inspect.json,weights.bin}; writes esp32/pi_gpt/model_weights.h.
The forward pass that consumes this is pi_gpt/pi_gpt.ino — a port of gpt.js.

INT8 is weight-only: matmul is  scale * sum(activation_f32 * weight_i8) + bias.
Simple and accurate; full int8 (activation quant + ESP-NN SIMD) is a later speed pass.
This header approach suits the small tiers; the 28.5M model will stream a binary
from a flash partition instead of compiling in.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

ap = argparse.ArgumentParser(description="Quantize a tier to a C header for the ESP32-S3.")
ap.add_argument("--tier", default="featherweight", help="tier id under web/tiers/")
ap.add_argument("--out", type=Path, default=HERE / "pi_gpt" / "model_weights.h")
args = ap.parse_args()

TDIR = ROOT / "web" / "tiers" / args.tier
inspect = json.loads((TDIR / "inspect.json").read_text(encoding="utf-8"))
cfg = inspect["config"]
V, C = cfg["vocab_size"], cfg["n_embd"]
L, H, BLK = cfg["n_layer"], cfg["n_head"], cfg["block_size"]

blob = np.fromfile(TDIR / "weights.bin", dtype="<f4")
man = {t["name"]: (t["offset"], t["count"]) for t in inspect["weights"]["tensors"]}
def tensor(name):
    off, cnt = man[name]
    return blob[off:off + cnt].astype(np.float64)

chars = [p["char"] for p in inspect["embedding"]["points"]]   # itos, in id order
assert len(chars) == V

# Which tensors go INT8 (the per-layer matmul weights — the bulk); the rest stay float.
INT8_SUFFIXES = ("attn.c_attn.weight", "attn.c_proj.weight", "mlp.c_fc.weight", "mlp.c_proj.weight")

def q_int8(w):
    """Symmetric per-tensor int8. Returns (int8 array, scale) with w ~= q*scale."""
    amax = float(np.max(np.abs(w))) or 1e-8
    scale = amax / 127.0
    q = np.clip(np.round(w / scale), -127, 127).astype(np.int8)
    err = float(np.max(np.abs(w - q * scale)) / amax)   # worst rel error
    return q, scale, err

# ---- emit the header ----------------------------------------------------------
out = []
w = out.append
w(f"// model_weights.h — generated by quantize.py from tier '{args.tier}'. Do not edit.")
w("// INT8 block weights (weight-only) + FP32 embeddings/head/norms. Consumed by pi_gpt.ino.")
w("#pragma once")
w("#include <stdint.h>")
w(f"#define N_LAYER {L}")
w(f"#define N_HEAD  {H}")
w(f"#define N_EMBD  {C}")
w(f"#define BLOCK   {BLK}")
w(f"#define VOCAB   {V}")
w(f"static const char VOCAB_CHARS[VOCAB] = {{ {', '.join(str(ord(c)) for c in chars)} }};")
w("")

def emit_f32(name, arr):
    vals = ", ".join(f"{x:.6g}" for x in np.asarray(arr, dtype=np.float32))
    w(f"static const float {name}[{len(arr)}] = {{ {vals} }};")

def emit_i8(name, q, scale):
    vals = ", ".join(str(int(x)) for x in q)
    w(f"static const int8_t {name}[{len(q)}] = {{ {vals} }};")
    w(f"static const float {name}_s = {scale:.9g}f;")

worst = 0.0
# top-level float tensors
emit_f32("tok_emb", tensor("tok_emb.weight"))
emit_f32("pos_emb", tensor("pos_emb.weight"))
emit_f32("ln_f_w", tensor("ln_f.weight"))
emit_f32("ln_f_b", tensor("ln_f.bias"))
emit_f32("head_w", tensor("head.weight"))
w("")
# per-layer
for l in range(L):
    p = f"blocks.{l}."
    emit_f32(f"L{l}_ln1_w", tensor(p + "ln1.weight")); emit_f32(f"L{l}_ln1_b", tensor(p + "ln1.bias"))
    for tag, suf in [("cattn", "attn.c_attn"), ("cproj", "attn.c_proj"), ("fc", "mlp.c_fc"), ("proj", "mlp.c_proj")]:
        q, s, e = q_int8(tensor(p + suf + ".weight")); worst = max(worst, e)
        emit_i8(f"L{l}_{tag}_w", q, s)
        emit_f32(f"L{l}_{tag}_b", tensor(p + suf + ".bias"))
    emit_f32(f"L{l}_ln2_w", tensor(p + "ln2.weight")); emit_f32(f"L{l}_ln2_b", tensor(p + "ln2.bias"))
w("")
# the layer table the forward pass loops over
w("typedef struct {")
w("  const float *ln1_w, *ln1_b;")
w("  const int8_t *cattn_w; float cattn_s; const float *cattn_b;")
w("  const int8_t *cproj_w; float cproj_s; const float *cproj_b;")
w("  const float *ln2_w, *ln2_b;")
w("  const int8_t *fc_w;    float fc_s;    const float *fc_b;")
w("  const int8_t *proj_w;  float proj_s;  const float *proj_b;")
w("} Layer;")
rows = []
for l in range(L):
    rows.append(
        f"  {{ L{l}_ln1_w, L{l}_ln1_b, "
        f"L{l}_cattn_w, L{l}_cattn_w_s, L{l}_cattn_b, "
        f"L{l}_cproj_w, L{l}_cproj_w_s, L{l}_cproj_b, "
        f"L{l}_ln2_w, L{l}_ln2_b, "
        f"L{l}_fc_w, L{l}_fc_w_s, L{l}_fc_b, "
        f"L{l}_proj_w, L{l}_proj_w_s, L{l}_proj_b }}")
w("static const Layer LAYERS[N_LAYER] = {\n" + ",\n".join(rows) + "\n};")

args.out.parent.mkdir(parents=True, exist_ok=True)
args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
kb = args.out.stat().st_size / 1024
print(f"tier {args.tier}: {L}L/{H}H/{C}d block {BLK} vocab {V}")
print(f"worst int8 rel error: {worst*100:.2f}%   (small = good)")
print(f"wrote {args.out}  ({kb:.0f} KB header)")
