"""
export_adapter.py  —  Convert the trained LoRA adapter to a GGUF adapter for Ollama.

WHY THIS EXISTS ALONGSIDE export_gguf.py
----------------------------------------
The browser needs a *merged* model. wllama exposes no adapter surface, so the
LoRA has to be folded back into the base weights and the whole ~500MB result
shipped. That is not a preference, it is the only thing wllama can load.

Ollama is different: it applies a LoRA adapter on top of a base model it already
has. So an Ollama user needs the adapter alone — ~50MB rather than ~500MB, and
the base is a file they very likely already downloaded. Same bake, a tenth of
the transfer, and the base stays reusable across every set of house rules you
ever bake.

    python export/export_adapter.py --config configs/qwen_coder_0_5b_chromebook.yaml

No GPU. The conversion reads the adapter's tensors and rewrites them in GGUF;
nothing is trained, merged or quantised, so this runs on the laptop that could
never have baked the thing in the first place.

THE ONE WAY THIS BITES
----------------------
An adapter is a *delta* against one specific set of base weights. Point it at a
different base and the numbers are meaningless. Ollama will not stop you at
build time: `ollama create` accepts a mismatched adapter and reports success.
The failure arrives later, when you first generate, as the model server exiting
(observed on Ollama 0.32.13 with a deliberately wrong-shaped adapter). So the
base model named in the Modelfile this script writes is taken from the same
config that trained the adapter, and should not be edited casually.
"""
from __future__ import annotations

import argparse
import logging
import subprocess
import sys
from pathlib import Path

import yaml

logger = logging.getLogger("rules_baker.export_adapter")

# ggml-org, not ggerganov — the repository moved, and the old path survives only
# through GitHub's redirect. Same URL the bake notebook clones.
LLAMA_CPP_URL = "https://github.com/ggml-org/llama.cpp"
CONVERTER = "convert_lora_to_gguf.py"


def ensure_llama_cpp(where: Path) -> Path:
    """Return a checkout of llama.cpp containing the LoRA converter, cloning if needed.

    Upstream's converter is used rather than a hand-rolled one on purpose. The
    hard part of this job is mapping PEFT's tensor names onto GGUF's, per
    architecture — llama.cpp already carries that table for every architecture
    it supports, and a copy of it here would go stale the first time a new base
    model appears in a config.
    """
    script = where / CONVERTER
    if script.exists():
        logger.info("Using existing llama.cpp checkout at %s", where)
        return script
    logger.info("Cloning llama.cpp into %s (shallow, for %s)", where, CONVERTER)
    subprocess.run(["git", "clone", "--depth", "1", LLAMA_CPP_URL, str(where)], check=True)
    if not script.exists():
        raise FileNotFoundError(
            f"{CONVERTER} is not in the llama.cpp checkout at {where}. "
            "The clone succeeded but the converter is missing — this usually means a "
            "very old checkout. Delete the directory and let it clone again."
        )
    return script


def converter_takes_base_model_id(script: Path) -> bool:
    """True if this llama.cpp checkout supports --base-model-id.

    Older checkouts only accept --base, a local directory of base-model config
    files. Asked rather than assumed, because guessing wrong turns a working
    conversion into an argparse error at the end of a long pipeline.

    Read from the source rather than by running `--help`: the converter imports
    torch at module scope, so on a machine without it `--help` fails with an
    ImportError, which would be indistinguishable here from "old checkout" and
    would send the caller down the wrong branch with a confident warning.
    """
    return "--base-model-id" in script.read_text(encoding="utf-8", errors="replace")


def write_modelfile(path: Path, ollama_base: str, trained_on: str,
                    adapter_name: str, system: str) -> None:
    """Write an Ollama Modelfile that stacks the adapter on the stock base.

    Written next to the adapter rather than checked in with the paths filled by
    hand, because a checked-in path is a path that goes stale the first time
    anyone changes output_dir. `export/Modelfile.adapter` is the readable
    example; this is the one that actually works.

    The adapter is referenced by bare filename: Ollama resolves a relative path
    against the directory holding the Modelfile, not the working directory
    (verified on 0.32.13), so this stays correct wherever `ollama create` runs.
    """
    path.write_text(
        f"# Generated by export_adapter.py — do not hand-edit; re-run the script.\n"
        f"#   ollama create <name> -f {path}\n"
        f"#\n"
        f"# FROM is the STOCK base model, unmodified. The house rules arrive via\n"
        f"# ADAPTER — about a tenth of the size, because everything the adapter does\n"
        f"# not change is already on this machine.\n"
        f"#\n"
        f"# This base must be the same weights the adapter was trained against:\n"
        f"#     {trained_on}\n"
        f"# A mismatch is not caught here. `ollama create` reports success and the\n"
        f"# failure arrives the first time you generate, as the model server exiting.\n"
        f"FROM {ollama_base}\n"
        f"ADAPTER ./{adapter_name}\n"
        f"\n"
        f"# The whole point: the rules are in the adapter, so the system prompt is\n"
        f"# one line instead of a style guide.\n"
        f'SYSTEM """{system}"""\n'
        f"\n"
        f"PARAMETER temperature 0.2\n"
        f"PARAMETER num_ctx 4096\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    ap = argparse.ArgumentParser(
        description="Convert the trained LoRA adapter to a GGUF adapter for Ollama.")
    ap.add_argument("--config", required=True, type=Path)
    ap.add_argument("--llama-cpp", type=Path, default=Path("llama.cpp"),
                    help="Where to find (or clone) llama.cpp. Default: ./llama.cpp")
    args = ap.parse_args(argv)

    cfg = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    exp = cfg.get("export", {})
    adapter_dir = Path(cfg["train"]["output_dir"]) / "adapter"

    if not (adapter_dir / "adapter_config.json").exists():
        logger.error(
            "No adapter at %s — train one first:\n"
            "    python train/train_lora.py --config %s",
            adapter_dir, args.config)
        return 1

    ollama_base = exp.get("ollama_base_model")
    if not ollama_base:
        logger.error(
            "config export.ollama_base_model is not set. It names the Ollama tag of the "
            "SAME base model the adapter was trained on (%s). Without it there is nothing "
            "safe to put in the Modelfile's FROM line.", cfg["student"]["base_model"])
        return 1

    out_name = f"{exp.get('ollama_model_name', 'housestyle')}-adapter.gguf"
    out_path = adapter_dir / out_name

    script = ensure_llama_cpp(args.llama_cpp)
    cmd = [sys.executable, str(script), str(adapter_dir),
           "--outfile", str(out_path), "--outtype", "f16"]
    if converter_takes_base_model_id(script):
        # The base's config.json is all the converter needs — it reads shapes and
        # architecture, never weights — so naming the Hub repo costs a small
        # download, not the model.
        cmd += ["--base-model-id", cfg["student"]["base_model"]]
    else:
        logger.warning(
            "This llama.cpp checkout has no --base-model-id; falling back to the "
            "base model recorded in adapter_config.json. If conversion fails, update "
            "the checkout at %s.", args.llama_cpp)
    logger.info("Converting: %s", " ".join(cmd))
    subprocess.run(cmd, check=True)

    modelfile = adapter_dir / "Modelfile"
    write_modelfile(
        modelfile, ollama_base, cfg["student"]["base_model"], out_name,
        "You are a senior Python engineer. Write clean, production-ready code.")

    size_mb = out_path.stat().st_size / 1e6
    logger.info("=" * 60)
    logger.info("adapter  -> %s (%.1f MB)", out_path, size_mb)
    logger.info("Modelfile -> %s", modelfile)
    logger.info("Serve it:")
    logger.info("    ollama pull %s", ollama_base)
    logger.info("    ollama create %s-adapter -f %s", exp.get("ollama_model_name"), modelfile)
    logger.info("Then generate once before you trust it — a base/adapter mismatch is")
    logger.info("reported at generation time, not by `ollama create`.")
    logger.info("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
